services:
    safesplit-mariadb:
        image: mariadb:11
        container_name: safesplit-mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: safesplit
            MARIADB_USER: safesplit
            MARIADB_PASSWORD: safesplit
        ports:
            - 33106:3306
        volumes:
            - ./.configs/mariadb-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            timeout: 5s
            retries: 20

    safesplit-phpmyadmin:
        image: phpmyadmin:latest
        container_name: safesplit-phpmyadmin
        restart: always
        environment:
            PMA_HOST: safesplit-mariadb
            PMA_USER: root
            PMA_PASSWORD: root
            UPLOAD_LIMIT: 512M
        ports:
            - 38080:80
        depends_on:
            - safesplit-mariadb
